In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#matplotlib.inline

In [2]:
data=pd.read_csv("/kaggle/input/house-prices-advanced-regression-techniques/train.csv")
data.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [3]:
data.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [4]:
data.describe()

Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1201.000000    1460.000000  1460.000000   
mean    730.500000    56.897260    70.049958   10516.828082     6.099315   
std     421.610009    42.300571    24.284752    9981.264932     1.382997   
min       1.000000    20.000000    21.000000    1300.000000     1.000000   
25%     365.750000    20.000000    59.000000    7553.500000     5.000000   
50%     730.500000    50.000000    69.000000    9478.500000     6.000000   
75%    1095.250000    70.000000    80.000000   11601.500000     7.000000   
max    1460.000000   190.000000   313.000000  215245.000000    10.000000   

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  ...  \
count  1460.000000  1460.000000   1460.000000  1452.000000  1460.000000  ...   
mean      5.575342  1971.267808   1984.865753   103.685262   443.639726  ...   
std       1.112799    30.202904     20.645407   181.066207   456.098091  ...   
min       1.000000  1872.000000   1950.000000     0.000000     0.000000  ...   
25%       5.000000  1954.000000   1967.000000     0.000000     0.000000  ...   
50%       5.000000  1973.000000   1994.000000     0.000000   383.500000  ...   
75%       6.000000  2000.000000   2004.000000   166.000000   712.250000  ...   
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000  ...   

        WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  ScreenPorch  \
count  1460.000000  1460.000000    1460.000000  1460.000000  1460.000000   
mean     94.244521    46.660274      21.954110     3.409589    15.060959   
std     125.338794    66.256028      61.119149    29.317331    55.757415   
min       0.000000     0.000000       0.000000     0.000000     0.000000   
25%       0.000000     0.000000       0.000000     0.000000     0.000000   
50%       0.000000    25.000000       0.000000     0.000000     0.000000   
75%     168.000000    68.000000       0.000000     0.000000     0.000000   
max     857.000000   547.000000     552.000000   508.000000   480.000000   

          PoolArea       MiscVal       MoSold       YrSold      SalePrice  
count  1460.000000   1460.000000  1460.000000  1460.000000    1460.000000  
mean      2.758904     43.489041     6.321918  2007.815753  180921.195890  
std      40.177307    496.123024     2.703626     1.328095   79442.502883  
min       0.000000      0.000000     1.000000  2006.000000   34900.000000  
25%       0.000000      0.000000     5.000000  2007.000000  129975.000000  
50%       0.000000      0.000000     6.000000  2008.000000  163000.000000  
75%       0.000000      0.000000     8.000000  2009.000000  214000.000000  
max     738.000000  15500.000000    12.000000  2010.000000  755000.000000  

[8 rows x 38 columns]

In [5]:
data.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   Alley          91 non-null     object 
 7   LotShape       1460 non-null   object 
 8   LandContour    1460 non-null   object 
 9   Utilities      1460 non-null   object 
 10  LotConfig      1460 non-null   object 
 11  LandSlope      1460 non-null   object 
 12  Neighborhood   1460 non-null   object 
 13  Condition1     1460 non-null   object 
 14  Condition2     1460 non-null   object 
 15  BldgType       1460 non-null   object 
 16  HouseStyle     1460 non-null   object 
 17  OverallQual    1460 non-null   int64  
 18  OverallC

In [7]:
data.drop(['PoolQC','Fence','MiscFeature','Alley','LotFrontage'],axis=1)

Id  MSSubClass MSZoning  LotArea Street LotShape LandContour  \
0        1          60       RL     8450   Pave      Reg         Lvl   
1        2          20       RL     9600   Pave      Reg         Lvl   
2        3          60       RL    11250   Pave      IR1         Lvl   
3        4          70       RL     9550   Pave      IR1         Lvl   
4        5          60       RL    14260   Pave      IR1         Lvl   
...    ...         ...      ...      ...    ...      ...         ...   
1455  1456          60       RL     7917   Pave      Reg         Lvl   
1456  1457          20       RL    13175   Pave      Reg         Lvl   
1457  1458          70       RL     9042   Pave      Reg         Lvl   
1458  1459          20       RL     9717   Pave      Reg         Lvl   
1459  1460          20       RL     9937   Pave      Reg         Lvl   

     Utilities LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch  \
0       AllPub    Inside       Gtl  ...             0         0           0   
1       AllPub       FR2       Gtl  ...             0         0           0   
2       AllPub    Inside       Gtl  ...             0         0           0   
3       AllPub    Corner       Gtl  ...           272         0           0   
4       AllPub       FR2       Gtl  ...             0         0           0   
...        ...       ...       ...  ...           ...       ...         ...   
1455    AllPub    Inside       Gtl  ...             0         0           0   
1456    AllPub    Inside       Gtl  ...             0         0           0   
1457    AllPub    Inside       Gtl  ...             0         0           0   
1458    AllPub    Inside       Gtl  ...           112         0           0   
1459    AllPub    Inside       Gtl  ...             0         0           0   

     PoolArea MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
0           0       0       2    2008        WD         Normal    208500  
1           0       0       5    2007        WD         Normal    181500  
2           0       0       9    2008        WD         Normal    223500  
3           0       0       2    2006        WD        Abnorml    140000  
4           0       0      12    2008        WD         Normal    250000  
...       ...     ...     ...     ...       ...            ...       ...  
1455        0       0       8    2007        WD         Normal    175000  
1456        0       0       2    2010        WD         Normal    210000  
1457        0    2500       5    2010        WD         Normal    266500  
1458        0       0       4    2010        WD         Normal    142125  
1459        0       0       6    2008        WD         Normal    147500  

[1460 rows x 76 columns]

In [8]:
data.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [9]:
data1=data[['MSSubClass','LotShape','HouseStyle','OverallQual','OverallCond','RoofStyle','Foundation','TotalBsmtSF','1stFlrSF','2ndFlrSF','GarageArea','PoolArea','SaleType']]

In [10]:
data1

MSSubClass LotShape HouseStyle  OverallQual  OverallCond RoofStyle  \
0             60      Reg     2Story            7            5     Gable   
1             20      Reg     1Story            6            8     Gable   
2             60      IR1     2Story            7            5     Gable   
3             70      IR1     2Story            7            5     Gable   
4             60      IR1     2Story            8            5     Gable   
...          ...      ...        ...          ...          ...       ...   
1455          60      Reg     2Story            6            5     Gable   
1456          20      Reg     1Story            6            6     Gable   
1457          70      Reg     2Story            7            9     Gable   
1458          20      Reg     1Story            5            6       Hip   
1459          20      Reg     1Story            5            6     Gable   

     Foundation  TotalBsmtSF  1stFlrSF  2ndFlrSF  GarageArea  PoolArea  \
0         PConc          856       856       854         548         0   
1        CBlock         1262      1262         0         460         0   
2         PConc          920       920       866         608         0   
3        BrkTil          756       961       756         642         0   
4         PConc         1145      1145      1053         836         0   
...         ...          ...       ...       ...         ...       ...   
1455      PConc          953       953       694         460         0   
1456     CBlock         1542      2073         0         500         0   
1457      Stone         1152      1188      1152         252         0   
1458     CBlock         1078      1078         0         240         0   
1459     CBlock         1256      1256         0         276         0   

     SaleType  
0          WD  
1          WD  
2          WD  
3          WD  
4          WD  
...       ...  
1455       WD  
1456       WD  
1457       WD  
1458       WD  
1459       WD  

[1460 rows x 13 columns]

In [11]:
numeric_data = data1.select_dtypes(include=[np.number])

In [12]:
numeric_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MSSubClass   1460 non-null   int64
 1   OverallQual  1460 non-null   int64
 2   OverallCond  1460 non-null   int64
 3   TotalBsmtSF  1460 non-null   int64
 4   1stFlrSF     1460 non-null   int64
 5   2ndFlrSF     1460 non-null   int64
 6   GarageArea   1460 non-null   int64
 7   PoolArea     1460 non-null   int64
dtypes: int64(8)
memory usage: 91.4 KB


In [13]:
numeric_data.skew()

MSSubClass      1.407657
OverallQual     0.216944
OverallCond     0.693067
TotalBsmtSF     1.524255
1stFlrSF        1.376757
2ndFlrSF        0.813030
GarageArea      0.179981
PoolArea       14.828374
dtype: float64

In [14]:
categorical_data = data1.select_dtypes(exclude=[np.number])

In [15]:
categorical_data

LotShape HouseStyle RoofStyle Foundation SaleType
0         Reg     2Story     Gable      PConc       WD
1         Reg     1Story     Gable     CBlock       WD
2         IR1     2Story     Gable      PConc       WD
3         IR1     2Story     Gable     BrkTil       WD
4         IR1     2Story     Gable      PConc       WD
...       ...        ...       ...        ...      ...
1455      Reg     2Story     Gable      PConc       WD
1456      Reg     1Story     Gable     CBlock       WD
1457      Reg     2Story     Gable      Stone       WD
1458      Reg     1Story       Hip     CBlock       WD
1459      Reg     1Story     Gable     CBlock       WD

[1460 rows x 5 columns]

In [16]:
categorical_data.isnull().sum()

LotShape      0
HouseStyle    0
RoofStyle     0
Foundation    0
SaleType      0
dtype: int64

In [17]:
categorical_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   LotShape    1460 non-null   object
 1   HouseStyle  1460 non-null   object
 2   RoofStyle   1460 non-null   object
 3   Foundation  1460 non-null   object
 4   SaleType    1460 non-null   object
dtypes: object(5)
memory usage: 57.2+ KB


In [18]:
categorical_data['LotShape'] = categorical_data['LotShape'].astype('category')
categorical_data['LotShape'] = categorical_data['LotShape'].cat.codes
categorical_data['LotShape']

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


0       3
1       3
2       0
3       0
4       0
       ..
1455    3
1456    3
1457    3
1458    3
1459    3
Name: LotShape, Length: 1460, dtype: int8

In [19]:
categorical_data['HouseStyle']= categorical_data['HouseStyle'].astype('category')
categorical_data['HouseStyle']= categorical_data['HouseStyle'].cat.codes
categorical_data['HouseStyle'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


array([5, 2, 0, 1, 6, 7, 4, 3], dtype=int8)

In [20]:
categorical_data['RoofStyle'] = categorical_data['RoofStyle'].astype('category')
categorical_data['RoofStyle']= categorical_data['RoofStyle'].cat.codes
categorical_data['RoofStyle'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


array([1, 3, 2, 4, 0, 5], dtype=int8)

In [21]:
categorical_data['Foundation'] = categorical_data['Foundation'].astype('category')
categorical_data['Foundation']= categorical_data['Foundation'].cat.codes
categorical_data['Foundation'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


array([2, 1, 0, 5, 3, 4], dtype=int8)

In [22]:
categorical_data['SaleType'] = categorical_data['SaleType'].astype('category')
categorical_data['SaleType']= categorical_data['SaleType'].cat.codes
categorical_data['SaleType'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


array([8, 6, 0, 3, 4, 1, 5, 2, 7], dtype=int8)

In [23]:
categorical_data

LotShape  HouseStyle  RoofStyle  Foundation  SaleType
0            3           5          1           2         8
1            3           2          1           1         8
2            0           5          1           2         8
3            0           5          1           0         8
4            0           5          1           2         8
...        ...         ...        ...         ...       ...
1455         3           5          1           2         8
1456         3           2          1           1         8
1457         3           5          1           4         8
1458         3           2          3           1         8
1459         3           2          1           1         8

[1460 rows x 5 columns]

In [24]:
numeric_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MSSubClass   1460 non-null   int64
 1   OverallQual  1460 non-null   int64
 2   OverallCond  1460 non-null   int64
 3   TotalBsmtSF  1460 non-null   int64
 4   1stFlrSF     1460 non-null   int64
 5   2ndFlrSF     1460 non-null   int64
 6   GarageArea   1460 non-null   int64
 7   PoolArea     1460 non-null   int64
dtypes: int64(8)
memory usage: 91.4 KB


In [25]:
train_data=pd.concat([numeric_data,categorical_data],axis=1)

In [26]:
train_data

MSSubClass  OverallQual  OverallCond  TotalBsmtSF  1stFlrSF  2ndFlrSF  \
0             60            7            5          856       856       854   
1             20            6            8         1262      1262         0   
2             60            7            5          920       920       866   
3             70            7            5          756       961       756   
4             60            8            5         1145      1145      1053   
...          ...          ...          ...          ...       ...       ...   
1455          60            6            5          953       953       694   
1456          20            6            6         1542      2073         0   
1457          70            7            9         1152      1188      1152   
1458          20            5            6         1078      1078         0   
1459          20            5            6         1256      1256         0   

      GarageArea  PoolArea  LotShape  HouseStyle  RoofStyle  Foundation  \
0            548         0         3           5          1           2   
1            460         0         3           2          1           1   
2            608         0         0           5          1           2   
3            642         0         0           5          1           0   
4            836         0         0           5          1           2   
...          ...       ...       ...         ...        ...         ...   
1455         460         0         3           5          1           2   
1456         500         0         3           2          1           1   
1457         252         0         3           5          1           4   
1458         240         0         3           2          3           1   
1459         276         0         3           2          1           1   

      SaleType  
0            8  
1            8  
2            8  
3            8  
4            8  
...        ...  
1455         8  
1456         8  
1457         8  
1458         8  
1459         8  

[1460 rows x 13 columns]

In [27]:
train_data.skew()

MSSubClass      1.407657
OverallQual     0.216944
OverallCond     0.693067
TotalBsmtSF     1.524255
1stFlrSF        1.376757
2ndFlrSF        0.813030
GarageArea      0.179981
PoolArea       14.828374
LotShape       -0.610175
HouseStyle      0.306755
RoofStyle       1.473796
Foundation      0.091217
SaleType       -3.868638
dtype: float64

In [28]:
X=train_data


In [29]:
X

MSSubClass  OverallQual  OverallCond  TotalBsmtSF  1stFlrSF  2ndFlrSF  \
0             60            7            5          856       856       854   
1             20            6            8         1262      1262         0   
2             60            7            5          920       920       866   
3             70            7            5          756       961       756   
4             60            8            5         1145      1145      1053   
...          ...          ...          ...          ...       ...       ...   
1455          60            6            5          953       953       694   
1456          20            6            6         1542      2073         0   
1457          70            7            9         1152      1188      1152   
1458          20            5            6         1078      1078         0   
1459          20            5            6         1256      1256         0   

      GarageArea  PoolArea  LotShape  HouseStyle  RoofStyle  Foundation  \
0            548         0         3           5          1           2   
1            460         0         3           2          1           1   
2            608         0         0           5          1           2   
3            642         0         0           5          1           0   
4            836         0         0           5          1           2   
...          ...       ...       ...         ...        ...         ...   
1455         460         0         3           5          1           2   
1456         500         0         3           2          1           1   
1457         252         0         3           5          1           4   
1458         240         0         3           2          3           1   
1459         276         0         3           2          1           1   

      SaleType  
0            8  
1            8  
2            8  
3            8  
4            8  
...        ...  
1455         8  
1456         8  
1457         8  
1458         8  
1459         8  

[1460 rows x 13 columns]

In [30]:
y=data.SalePrice

In [31]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [32]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [33]:
y_pred=regressor.predict(x_test)

In [34]:
y_pred

array([214348.10797571, 110342.12366108, 135043.05305775, 275628.91065506,
       175724.96606283, 116407.76302114, 174721.18127399, 102074.5940915 ,
       224928.14836392, 217539.0836055 , 241671.29921025,  93635.02615047,
       130411.28675746, 258136.64664241, 154349.40053905, 206204.62971094,
       185476.74942041, 125653.9351502 , 203574.20203636, 168670.54107597,
       168010.81728445,  69404.34313389, 147819.30109344, 125716.32476197,
       122912.58634277, 256777.53120069, 217011.41244328, 121211.41496016,
       220251.9133335 , 124258.79669297, 274301.07464045, 206443.43762567,
       146314.34968528, 148667.94278216, 192072.77625986, 215202.33341932,
       221917.82519344, 119948.96915115, 267529.55650892, 175396.95088719,
       190828.30424615, 218025.87455012, 262751.46682444, 186339.06119908,
       215590.45906991, 163751.23168656, 221628.72470375, 130411.28675746,
       107216.31096496, 131793.54336166, 144807.06544092, 177081.34494604,
       198574.35585701, 2

In [35]:

regressor.score(x_test,y_test)

0.7157373525374651

In [36]:
test_data=pd.read_csv("/kaggle/input/house-prices-advanced-regression-techniques/test.csv")

In [37]:
test_data

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0     1461          20       RH         80.0    11622   Pave   NaN      Reg   
1     1462          20       RL         81.0    14267   Pave   NaN      IR1   
2     1463          60       RL         74.0    13830   Pave   NaN      IR1   
3     1464          60       RL         78.0     9978   Pave   NaN      IR1   
4     1465         120       RL         43.0     5005   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1454  2915         160       RM         21.0     1936   Pave   NaN      Reg   
1455  2916         160       RM         21.0     1894   Pave   NaN      Reg   
1456  2917          20       RL        160.0    20000   Pave   NaN      Reg   
1457  2918          85       RL         62.0    10441   Pave   NaN      Reg   
1458  2919          60       RL         74.0     9627   Pave   NaN      Reg   

     LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence  \
0            Lvl    AllPub  ...         120        0    NaN  MnPrv   
1            Lvl    AllPub  ...           0        0    NaN    NaN   
2            Lvl    AllPub  ...           0        0    NaN  MnPrv   
3            Lvl    AllPub  ...           0        0    NaN    NaN   
4            HLS    AllPub  ...         144        0    NaN    NaN   
...          ...       ...  ...         ...      ...    ...    ...   
1454         Lvl    AllPub  ...           0        0    NaN    NaN   
1455         Lvl    AllPub  ...           0        0    NaN    NaN   
1456         Lvl    AllPub  ...           0        0    NaN    NaN   
1457         Lvl    AllPub  ...           0        0    NaN  MnPrv   
1458         Lvl    AllPub  ...           0        0    NaN    NaN   

     MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition  
0            NaN       0      6    2010        WD         Normal  
1           Gar2   12500      6    2010        WD         Normal  
2            NaN       0      3    2010        WD         Normal  
3            NaN       0      6    2010        WD         Normal  
4            NaN       0      1    2010        WD         Normal  
...          ...     ...    ...     ...       ...            ...  
1454         NaN       0      6    2006        WD         Normal  
1455         NaN       0      4    2006        WD        Abnorml  
1456         NaN       0      9    2006        WD        Abnorml  
1457        Shed     700      7    2006        WD         Normal  
1458         NaN       0     11    2006        WD         Normal  

[1459 rows x 80 columns]

In [38]:
data1=test_data[['MSSubClass','LotShape','HouseStyle','OverallQual','OverallCond','RoofStyle','Foundation','TotalBsmtSF','1stFlrSF','2ndFlrSF','GarageArea','PoolArea','SaleType']]

In [39]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1459 non-null   int64  
 1   LotShape     1459 non-null   object 
 2   HouseStyle   1459 non-null   object 
 3   OverallQual  1459 non-null   int64  
 4   OverallCond  1459 non-null   int64  
 5   RoofStyle    1459 non-null   object 
 6   Foundation   1459 non-null   object 
 7   TotalBsmtSF  1458 non-null   float64
 8   1stFlrSF     1459 non-null   int64  
 9   2ndFlrSF     1459 non-null   int64  
 10  GarageArea   1458 non-null   float64
 11  PoolArea     1459 non-null   int64  
 12  SaleType     1458 non-null   object 
dtypes: float64(2), int64(6), object(5)
memory usage: 148.3+ KB


In [40]:
data1.isnull().sum()

MSSubClass     0
LotShape       0
HouseStyle     0
OverallQual    0
OverallCond    0
RoofStyle      0
Foundation     0
TotalBsmtSF    1
1stFlrSF       0
2ndFlrSF       0
GarageArea     1
PoolArea       0
SaleType       1
dtype: int64

In [41]:
numeric_data1 = data1.select_dtypes(include=[np.number])
categorical_data1 = data1.select_dtypes(exclude=[np.number])

In [42]:
numeric_data1

MSSubClass  OverallQual  OverallCond  TotalBsmtSF  1stFlrSF  2ndFlrSF  \
0             20            5            6        882.0       896         0   
1             20            6            6       1329.0      1329         0   
2             60            5            5        928.0       928       701   
3             60            6            6        926.0       926       678   
4            120            8            5       1280.0      1280         0   
...          ...          ...          ...          ...       ...       ...   
1454         160            4            7        546.0       546       546   
1455         160            4            5        546.0       546       546   
1456          20            5            7       1224.0      1224         0   
1457          85            5            5        912.0       970         0   
1458          60            7            5        996.0       996      1004   

      GarageArea  PoolArea  
0          730.0         0  
1          312.0         0  
2          482.0         0  
3          470.0         0  
4          506.0         0  
...          ...       ...  
1454         0.0         0  
1455       286.0         0  
1456       576.0         0  
1457         0.0         0  
1458       650.0         0  

[1459 rows x 8 columns]

In [43]:
numeric_data1.isnull().sum()

MSSubClass     0
OverallQual    0
OverallCond    0
TotalBsmtSF    1
1stFlrSF       0
2ndFlrSF       0
GarageArea     1
PoolArea       0
dtype: int64

In [44]:
numeric_data1['TotalBsmtSF']=numeric_data1['TotalBsmtSF'].fillna(0)
numeric_data1['TotalBsmtSF'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


array([ 882., 1329.,  928.,  926., 1280.,  763., 1168.,  789., 1300.,
       1405.,  483.,  525.,  855.,  836., 1590., 1544., 1698., 1822.,
       2846., 1671., 1370., 1324., 1145.,  384.,  847., 1629., 1595.,
       1218., 1468.,  831.,  816., 1208., 1231., 1390., 1488.,  840.,
        600.,  756.,  530., 1642.,  975., 1492., 1829., 1224.,  715.,
       1232., 1209., 1510.,  533., 1728., 1140.,  782., 1080., 1604.,
       1480., 1143., 1206., 1244.,  832.,  864.,  972.,  988.,  576.,
       1175., 1395.,  709.,  936., 1347.,  827., 1027., 1008.,  678.,
        930.,  346.,  738., 1108.,  765.,  608.,  572.,  835.,  780.,
        528., 1124.,  888.,  662., 1422.,  689., 1212.,  707.,  856.,
       1832., 1319.,  720., 1420.,  660., 1117.,  663., 1172., 1508.,
       1250., 1433.,  946., 1222.,  676.,  870.,  878., 1026.,  876.,
       1978., 1040.,  848.,    0.,  381., 1196.,  744.,  960., 1107.,
        894., 1528., 1032.,  423.,  982., 1191.,  480.,  629., 1594.,
       1049., 1243.,

In [45]:
numeric_data1['GarageArea']=numeric_data1['GarageArea'].fillna(0)
numeric_data1['GarageArea'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


array([ 730.,  312.,  482.,  470.,  506.,  440.,  420.,  393.,  525.,
        511.,  264.,  320.,  308.,  751.,  868.,  678.,  958.,  756.,
        484.,  430.,  437.,  400.,  433.,  962.,  880.,  676.,  528.,
        429.,  461.,  762.,  713.,  588.,  480.,  496.,  852.,  592.,
        596.,  535.,  660.,  441.,  490.,  504.,  517.,    0.,  315.,
        576.,  620.,  263.,  318.,  305.,  280.,  240.,  551.,  780.,
        288.,  624.,  363.,  200.,  572.,  180.,  365.,  231.,  450.,
        416.,  591.,  690.,  522.,  467.,  209.,  366., 1017.,  615.,
        580.,  513.,  850.,  621.,  319.,  336.,  352.,  260.,  399.,
        473.,  598.,  531.,  625.,  330.,  741.,  776.,  520.,  686.,
        253.,  286.,  495.,  616.,  275.,  502.,  632.,  390.,  564.,
        396.,  409.,  567.,  529.,  479.,  581.,  565.,  478.,  477.,
        345.,  656.,  754.,  864.,  896.,  834.,  932.,  640.,  927.,
        700.,  583.,  886.,  871.,  949.,  685.,  649.,  539.,  701.,
        392.,  397.,

In [46]:
numeric_data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1459 non-null   int64  
 1   OverallQual  1459 non-null   int64  
 2   OverallCond  1459 non-null   int64  
 3   TotalBsmtSF  1459 non-null   float64
 4   1stFlrSF     1459 non-null   int64  
 5   2ndFlrSF     1459 non-null   int64  
 6   GarageArea   1459 non-null   float64
 7   PoolArea     1459 non-null   int64  
dtypes: float64(2), int64(6)
memory usage: 91.3 KB


In [47]:
categorical_data1

LotShape HouseStyle RoofStyle Foundation SaleType
0         Reg     1Story     Gable     CBlock       WD
1         IR1     1Story       Hip     CBlock       WD
2         IR1     2Story     Gable      PConc       WD
3         IR1     2Story     Gable      PConc       WD
4         IR1     1Story     Gable      PConc       WD
...       ...        ...       ...        ...      ...
1454      Reg     2Story     Gable     CBlock       WD
1455      Reg     2Story     Gable     CBlock       WD
1456      Reg     1Story     Gable     CBlock       WD
1457      Reg     SFoyer     Gable      PConc       WD
1458      Reg     2Story     Gable      PConc       WD

[1459 rows x 5 columns]

In [48]:
categorical_data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   LotShape    1459 non-null   object
 1   HouseStyle  1459 non-null   object
 2   RoofStyle   1459 non-null   object
 3   Foundation  1459 non-null   object
 4   SaleType    1458 non-null   object
dtypes: object(5)
memory usage: 57.1+ KB


In [49]:
categorical_data1.isnull().sum()

LotShape      0
HouseStyle    0
RoofStyle     0
Foundation    0
SaleType      1
dtype: int64

In [50]:
categorical_data1['SaleType'].unique()

array(['WD', 'COD', 'New', 'ConLD', 'Oth', 'Con', 'ConLw', 'ConLI', 'CWD',
       nan], dtype=object)

In [51]:
categorical_data1['SaleType']=categorical_data1['SaleType'].fillna('COD')
categorical_data1['SaleType'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


array(['WD', 'COD', 'New', 'ConLD', 'Oth', 'Con', 'ConLw', 'ConLI', 'CWD'],
      dtype=object)

In [52]:
categorical_data1.isnull().sum()

LotShape      0
HouseStyle    0
RoofStyle     0
Foundation    0
SaleType      0
dtype: int64

In [53]:
categorical_data1['SaleType'] = categorical_data1['SaleType'].astype('category')
categorical_data1['SaleType']= categorical_data1['SaleType'].cat.codes
categorical_data1['SaleType'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


array([8, 0, 6, 3, 7, 2, 5, 4, 1], dtype=int8)

In [54]:
categorical_data1['Foundation'] = categorical_data1['Foundation'].astype('category')
categorical_data1['Foundation']= categorical_data1['Foundation'].cat.codes
categorical_data1['Foundation'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


array([1, 2, 0, 4, 3, 5], dtype=int8)

In [55]:
categorical_data1['RoofStyle'] = categorical_data1['RoofStyle'].astype('category')
categorical_data1['RoofStyle']= categorical_data1['RoofStyle'].cat.codes
categorical_data1['RoofStyle'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


array([1, 3, 2, 0, 4, 5], dtype=int8)

In [56]:
categorical_data1['HouseStyle']= categorical_data1['HouseStyle'].astype('category')
categorical_data1['HouseStyle']= categorical_data1['HouseStyle'].cat.codes
categorical_data1['HouseStyle'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


array([2, 4, 6, 0, 5, 3, 1], dtype=int8)

In [57]:
categorical_data1['LotShape'] = categorical_data1['LotShape'].astype('category')
categorical_data1['LotShape'] = categorical_data1['LotShape'].cat.codes
categorical_data1['LotShape'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


array([3, 0, 1, 2], dtype=int8)

In [58]:
test_data1=pd.concat([numeric_data1,categorical_data1],axis=1)

In [59]:
test_data1.head()

MSSubClass  OverallQual  OverallCond  TotalBsmtSF  1stFlrSF  2ndFlrSF  \
0          20            5            6        882.0       896         0   
1          20            6            6       1329.0      1329         0   
2          60            5            5        928.0       928       701   
3          60            6            6        926.0       926       678   
4         120            8            5       1280.0      1280         0   

   GarageArea  PoolArea  LotShape  HouseStyle  RoofStyle  Foundation  SaleType  
0       730.0         0         3           2          1           1         8  
1       312.0         0         0           2          3           1         8  
2       482.0         0         0           4          1           2         8  
3       470.0         0         0           4          1           2         8  
4       506.0         0         0           2          1           2         8

In [60]:
test=regressor.predict(test_data1)

In [61]:
test

array([134630.86308986, 179883.25287566, 166605.49224374, ...,
       153805.08764417, 100832.70030886, 231580.22664813])

In [62]:
sub=pd.DataFrame({"Id":test_data.Id,"SalePrice":test})

In [63]:
sub

Id      SalePrice
0     1461  134630.863090
1     1462  179883.252876
2     1463  166605.492244
3     1464  191900.722373
4     1465  218283.155988
...    ...            ...
1454  2915   61339.678059
1455  2916   67816.046354
1456  2917  153805.087644
1457  2918  100832.700309
1458  2919  231580.226648

[1459 rows x 2 columns]

In [64]:
sub.to_csv('submission.csv',index=False)